language: php
php:
  - 7.1
os:
  - linux
sudo: enabled
install: 
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/ubuntu trusty main" | sudo tee /etc/apt/sources.list.d/mono-official.list
  - sudo apt-get update
  - sudo apt-get install mono-devel -y
  - wget https://github.com/GitTools/GitVersion/releases/download/v4.0.0-beta.12/GitVersion_4.0.0-beta0012.zip
  - unzip GitVersion_4.0.0-beta0012.zip
  - mono GitVersion.exe /l console /output buildserver /nofetch
  - echo "The version is " %GitVersion_SemVer%
  - echo "%GitVersion_SemVer%"
  - echo $GitVersion_SemVer
  - echo "${GitVersion_SemVer}"
script: true
after_script: true